import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

final class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('es'), Locale('pt')];

  static const LocalizationsDelegate<AppStrings> delegate = _StringsDelegate();

  static AppStrings of(BuildContext context) {
    return Localizations.of<AppStrings>(context, AppStrings)!;
  }

  String text(String key) {
    final language = _values.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _values[language]?[key] ?? _values['en']?[key] ?? key;
  }

  static const _values = <String, Map<String, String>>{
    'en': {
      'appName': 'EnergyCore',
      'tagline': 'Smarter energy. Clearer decisions.',
      'authVisualMessage':
          'Monitor consumption, reduce waste, and keep every space under control.',
      'signIn': 'Sign in',
      'signUp': 'Create account',
      'recover': 'Recover password',
      'welcome': 'Welcome back',
      'createTitle': 'Power up your space',
      'recoverTitle': 'Recover access',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full name',
      'forgot': 'Forgot password?',
      'noAccount': 'New to EnergyCore?',
      'hasAccount': 'Already have an account?',
      'backToLogin': 'Back to sign in',
      'sendRecovery': 'Send recovery email',
      'recoverySent': 'If the account exists, recovery instructions were sent.',
      'required': 'This field is required.',
      'invalidEmail': 'Enter a valid email.',
      'shortPassword': 'Use at least 8 characters.',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'home': 'Home',
      'energy': 'Energy',
      'devices': 'Devices',
      'alerts': 'Alerts',
      'more': 'More',
      'greeting': 'Hello',
      'overview': 'Your energy, right now',
      'live': 'LIVE',
      'currentPower': 'Current power',
      'todayEnergy': 'Energy today',
      'todayCost': 'Cost today',
      'monthlyProjection': 'Monthly projection',
      'efficiency': 'Efficiency',
      'activeDevices': 'Active devices',
      'trend': 'Consumption trend',
      'topDevices': 'Top-consuming devices',
      'rooms': 'Consumption by room',
      'recommendation': 'Energy insight',
      'noData': 'No energy data is available yet.',
      'retry': 'Retry',
      'offline': 'Internet connection required to update EnergyCore.',
      'loadError': 'We could not load your energy information.',
      'language': 'Language',
      'appearance': 'Appearance',
      'systemTheme': 'Follows your device settings',
      'account': 'Account',
      'signOut': 'Sign out',
      'profile': 'Profile',
      'emptyHint':
          'Create your first item to start connecting your energy operation.',
      'refresh': 'Refresh',
      'operations': 'Operations',
      'deviceControlTitle': 'Connected operations',
      'deviceControlDescription':
          'Control devices, groups, routines and operating modes from one place.',
      'groups': 'Groups',
      'routines': 'Routines',
      'modes': 'Modes',
      'noDevices': 'No devices connected',
      'noGroups': 'No device groups',
      'noRoutines': 'No routines scheduled',
      'noModes': 'No operating modes',
      'newMode': 'New mode',
      'turnOn': 'Turn on',
      'turnOff': 'Turn off',
      'pairDevice': 'Pair device',
      'pairingCode': 'Pairing code',
      'deviceName': 'Device name',
      'room': 'Room',
      'connect': 'Connect',
      'cancel': 'Cancel',
      'newGroup': 'New group',
      'name': 'Name',
      'description': 'Description',
      'save': 'Save',
      'newRoutine': 'New routine',
      'schedule': 'Schedule',
      'runNow': 'Run now',
      'allDay': 'All day',
      'targetType': 'Target type',
      'target': 'Target',
      'repeat': 'Repeat',
      'once': 'Once',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'customInterval': 'Custom interval',
      'daysOfWeek': 'Days of the week',
      'intervalDays': 'Interval in days',
      'startsOn': 'Starts on',
      'mondayShort': 'Mon',
      'tuesdayShort': 'Tue',
      'wednesdayShort': 'Wed',
      'thursdayShort': 'Thu',
      'fridayShort': 'Fri',
      'saturdayShort': 'Sat',
      'sundayShort': 'Sun',
      'modeDetails': 'Mode details and scope',
      'entireSite': 'Entire site',
      'startTime': 'Start time',
      'endTime': 'End time',
      'internalRoutines': 'Mode routines',
      'routineName': 'Routine name',
      'triggerTime': 'Trigger time',
      'addRoutine': 'Add routine',
      'automationPolicies': 'Goals and notification policies',
      'applyRuleProfile': 'Apply an alert rule profile',
      'ruleProfile': 'Rule profile',
      'applyNotificationPreference': 'Apply my notification preferences',
      'preserveCriticalSound': 'Keep sound for critical alerts',
      'createMode': 'Create mode',
      'activate': 'Activate',
      'spaces': 'Spaces',
      'sites': 'Sites',
      'assignments': 'Assignments',
      'noSites': 'No sites configured',
      'noRooms': 'No rooms configured',
      'noAssignments': 'No device assignments',
      'newSite': 'New site',
      'address': 'Address',
      'type': 'Type',
      'newRoom': 'New room',
      'floor': 'Floor',
      'assignDevice': 'Assign device',
      'noRoom': 'No room',
      'unassign': 'Unassign',
      'delete': 'Delete',
      'deleteSite': 'Delete site',
      'deleteSiteWarning': 'This can affect its rooms and device assignments.',
      'deleteRoom': 'Delete room',
      'deleteRoomWarning':
          'Devices assigned to this room may become unassigned.',
      'notifications': 'Notifications',
      'alertsCenter': 'Alert center',
      'alertsDescription':
          'Review alerts, automate rules and choose how EnergyCore reaches you.',
      'inbox': 'Inbox',
      'rules': 'Rules',
      'preferences': 'Preferences',
      'noAlerts': 'Your inbox is clear',
      'noRules': 'No alert rules',
      'markRead': 'Mark read',
      'resolve': 'Resolve',
      'dismiss': 'Dismiss',
      'newRule': 'New rule',
      'metric': 'Metric',
      'condition': 'Condition',
      'threshold': 'Threshold',
      'severity': 'Severity',
      'pushNotifications': 'Push notifications',
      'inApp': 'In-app notifications',
      'criticalOnly': 'Critical alerts only',
      'quietHours': 'Quiet hours',
      'dailySummary': 'Daily summary',
      'weeklySummary': 'Weekly summary',
      'monthlyReport': 'Monthly report',
      'savePreferences': 'Save preferences',
      'energyCenter': 'Energy intelligence',
      'energyCenterDescription':
          'Explore live consumption, history, reports and reduction goals.',
      'consumption': 'Consumption',
      'history': 'History',
      'reports': 'Reports',
      'goals': 'Goals',
      'noReadings': 'No energy readings',
      'searchDevice': 'Search by device',
      'unknownDate': 'Unknown date',
      'noReports': 'No reports generated',
      'report': 'Report',
      'total': 'Total',
      'average': 'Average',
      'peak': 'Peak',
      'generateReport': 'Generate report',
      'startDate': 'Start date',
      'endDate': 'End date',
      'generate': 'Generate',
      'noGoals': 'No energy goals',
      'newGoal': 'New goal',
      'targetKwh': 'Target (kWh)',
      'deadline': 'Deadline',
      'service': 'Service',
      'support': 'Support',
      'maintenance': 'Maintenance',
      'noSupportTickets': 'No support tickets',
      'noMaintenanceTickets': 'No maintenance visits',
      'newTicket': 'New ticket',
      'subject': 'Subject',
      'priority': 'Priority',
      'send': 'Send',
      'scheduleMaintenance': 'Schedule maintenance',
      'scheduledDate': 'Scheduled date',
      'complete': 'Complete',
      'billing': 'Billing',
      'plans': 'Plans',
      'payments': 'Payments',
      'invoices': 'Invoices',
      'noPlans': 'No plans available',
      'noPayments': 'No payments yet',
      'noInvoices': 'No invoices yet',
      'currentPlan': 'Current plan',
      'choosePlan': 'Choose plan',
      'cancelPlan': 'Cancel plan',
      'cancelSubscription': 'Cancel subscription',
      'cancelSubscriptionWarning':
          'Your access may change when the current billing period ends.',
      'confirm': 'Confirm',
      'cardHolder': 'Cardholder name',
      'cardNumber': 'Card number',
      'subscribe': 'Subscribe',
      'active': 'Active',
      'security': 'Security',
      'access': 'Access',
      'platform': 'Platform',
      'editProfile': 'Edit profile',
      'changePassword': 'Change password',
      'changePasswordDescription': 'Receive a secure reset link by email.',
      'deleteAccount': 'Delete account',
      'deleteAccountWarning':
          'This permanently removes your EnergyCore account.',
      'accessRestricted':
          'Access management is available only to authorized profiles.',
      'platformTitle': 'One connected energy system',
      'platformDescription':
          'EnergyCore connects spaces, devices, automation, alerts and decisions through the Teralume platform.',
      'energyMonitoring': 'Real-time energy monitoring',
      'deviceAutomation': 'Devices, groups, routines and modes',
      'smartAlerts': 'Rules and intelligent alerts',
      'reportsAndGoals': 'Reports and energy goals',
      'integratedSupport': 'Integrated support and maintenance',
      'operationalCenterDescription':
          'Everything important in your energy operation, in one clear view.',
      'setupGuide': 'Complete your setup',
      'welcomeEnergyCore': 'Welcome to EnergyCore',
      'homeEmptyDescription':
          'Connect the backend and start adding spaces and devices to see your operation come alive.',
      'unread': 'Unread',
      'activeRules': 'Active rules',
      'noActiveMode': 'No active mode',
      'available': 'Available',
      'open': 'Open',
      'spacesDescription': 'Sites, rooms and assignments',
      'serviceDescription': 'Support and maintenance',
      'billingDescription': 'Plans and payment history',
      'accountDescription': 'Profile, security and access',
      'moreDescription': 'Manage the rest of your EnergyCore experience.',
      'edit': 'Edit',
      'addDevice': 'Add device',
      'createDevice': 'Create device',
      'editDevice': 'Edit device',
      'powerWatts': 'Power (W)',
      'deleteDevice': 'Delete device',
      'deleteDeviceWarning': 'This device and its links will be removed.',
      'editGroup': 'Edit group',
      'deleteGroup': 'Delete group',
      'deleteGroupWarning':
          'The group will be removed without deleting its devices.',
      'deleteRoutine': 'Delete routine',
      'deleteRoutineWarning': 'This automation will stop running.',
      'preview': 'Preview',
      'archive': 'Archive',
      'affectedDevices': 'Affected devices',
      'ignoredDevices': 'Ignored devices',
      'close': 'Close',
      'archiveMode': 'Archive mode',
      'archiveModeWarning': 'This operating mode will no longer be available.',
      'editSite': 'Edit site',
      'editRoom': 'Edit room',
      'move': 'Move',
      'moveDevice': 'Move device',
      'deleteTicket': 'Delete ticket',
      'deleteTicketWarning':
          'This support request will be permanently removed.',
      'deleteMaintenance': 'Delete maintenance',
      'details': 'Details',
      'export': 'Export',
      'deviceBreakdown': 'Device breakdown',
      'copiedToClipboard': 'CSV copied to clipboard.',
      'editGoal': 'Edit goal',
      'currentKwh': 'Current (kWh)',
      'status': 'Status',
      'dateRange': 'Date range',
      'all': 'All',
      'newest': 'Newest',
      'oldest': 'Oldest',
      'power_desc': 'Highest power',
      'power_asc': 'Lowest power',
      'powerRange': 'Power range',
      'minimum': 'Minimum',
      'maximum': 'Maximum',
      'apply': 'Apply',
      'samplingInterval': 'Sampling interval',
      'seconds': 'seconds',
      'critical': 'Critical',
      'evidence': 'Evidence',
      'explanation': 'Explanation',
      'recommendedAction': 'Recommended action',
      'deleteAlert': 'Delete alert',
      'deleteAlertWarning': 'This alert will be permanently removed.',
      'inactive': 'Inactive',
      'newProfile': 'New profile',
      'evaluateRules': 'Evaluate rules',
      'deleteRule': 'Delete rule',
      'deleteRuleWarning': 'This alert rule will be permanently removed.',
      'mode': 'Mode',
      'sensitivity': 'Sensitivity',
      'observedValue': 'Observed value',
      'evaluate': 'Evaluate',
      'evaluationResult': 'Evaluation result',
      'minimumLevel': 'Minimum level',
      'toastNotifications': 'Floating notifications',
      'dashboardNotifications': 'Dashboard notifications',
      'allowedLevels': 'Allowed alert levels',
      'allowedSources': 'Allowed sources',
      'criticalBreaksQuietHours': 'Critical alerts break quiet hours',
      'routineNightSilence': 'Silence routine alerts at night',
      'goalDeadlineAlerts': 'Energy goal deadline alerts',
      'maintenanceDeviceAlerts': 'Device maintenance alerts',
      'systemRecommendations': 'System recommendations',
      'deliveryMode': 'Default delivery mode',
      'groupSimilarAlerts': 'Group similar alerts',
      'reminders': 'Reminders',
      'cooldownMinutes': 'Cooldown (minutes)',
      'maxAlertsPerHour': 'Maximum alerts per hour',
      'resetPasswordTitle': 'Set a new password',
      'resetPassword': 'Reset password',
      'recoveryToken': 'Recovery token',
      'confirmPassword': 'Confirm password',
      'passwordsDoNotMatch': 'Passwords do not match.',
      'haveRecoveryToken': 'I already have a recovery token',
      'passwordResetSuccess': 'Password updated. You can now sign in.',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'chooseAPlan': 'Choose a plan to continue',
      'exportInvoice': 'Export invoice',
      'invoiceCopied': 'Invoice copied to clipboard.',
      'newAlert': 'New alert',
      'title': 'Title',
      'message': 'Message',
      'upgradePlanFeature': 'Upgrade your plan to use this feature.',
      'searchAddress': 'Search address',
    },
    'es': {
      'appName': 'EnergyCore',
      'tagline': 'Energía inteligente. Decisiones claras.',
      'authVisualMessage':
          'Monitorea el consumo, reduce desperdicios y mantén cada espacio bajo control.',
      'signIn': 'Iniciar sesión',
      'signUp': 'Crear cuenta',
      'recover': 'Recuperar contraseña',
      'welcome': 'Bienvenido de nuevo',
      'createTitle': 'Dale energía a tu espacio',
      'recoverTitle': 'Recupera tu acceso',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'fullName': 'Nombre completo',
      'forgot': '¿Olvidaste tu contraseña?',
      'noAccount': '¿Primera vez en EnergyCore?',
      'hasAccount': '¿Ya tienes una cuenta?',
      'backToLogin': 'Volver al inicio',
      'sendRecovery': 'Enviar correo de recuperación',
      'recoverySent': 'Si la cuenta existe, enviamos las instrucciones.',
      'required': 'Este campo es obligatorio.',
      'invalidEmail': 'Ingresa un correo válido.',
      'shortPassword': 'Usa al menos 8 caracteres.',
      'showPassword': 'Mostrar contraseña',
      'hidePassword': 'Ocultar contraseña',
      'home': 'Inicio',
      'energy': 'Energía',
      'devices': 'Dispositivos',
      'alerts': 'Alertas',
      'more': 'Más',
      'greeting': 'Hola',
      'overview': 'Tu energía, ahora mismo',
      'live': 'EN VIVO',
      'currentPower': 'Potencia actual',
      'todayEnergy': 'Energía de hoy',
      'todayCost': 'Costo de hoy',
      'monthlyProjection': 'Proyección mensual',
      'efficiency': 'Eficiencia',
      'activeDevices': 'Dispositivos activos',
      'trend': 'Tendencia de consumo',
      'topDevices': 'Dispositivos con mayor consumo',
      'rooms': 'Consumo por habitación',
      'recommendation': 'Consejo energético',
      'noData': 'Aún no hay datos de consumo disponibles.',
      'retry': 'Reintentar',
      'offline': 'Necesitas internet para actualizar EnergyCore.',
      'loadError': 'No pudimos cargar tu información energética.',
      'language': 'Idioma',
      'appearance': 'Apariencia',
      'systemTheme': 'Sigue la configuración del dispositivo',
      'account': 'Cuenta',
      'signOut': 'Cerrar sesión',
      'profile': 'Perfil',
      'emptyHint':
          'Crea el primer elemento para conectar tu operación energética.',
      'refresh': 'Actualizar',
      'operations': 'Operaciones',
      'deviceControlTitle': 'Operaciones conectadas',
      'deviceControlDescription':
          'Controla dispositivos, grupos, rutinas y modos desde un solo lugar.',
      'groups': 'Grupos',
      'routines': 'Rutinas',
      'modes': 'Modos',
      'noDevices': 'No hay dispositivos conectados',
      'noGroups': 'No hay grupos de dispositivos',
      'noRoutines': 'No hay rutinas programadas',
      'noModes': 'No hay modos de operación',
      'newMode': 'Nuevo modo',
      'turnOn': 'Encender',
      'turnOff': 'Apagar',
      'pairDevice': 'Vincular dispositivo',
      'pairingCode': 'Código de vinculación',
      'deviceName': 'Nombre del dispositivo',
      'room': 'Habitación',
      'connect': 'Conectar',
      'cancel': 'Cancelar',
      'newGroup': 'Nuevo grupo',
      'name': 'Nombre',
      'description': 'Descripción',
      'save': 'Guardar',
      'newRoutine': 'Nueva rutina',
      'schedule': 'Horario',
      'runNow': 'Ejecutar ahora',
      'allDay': 'Todo el día',
      'targetType': 'Tipo de objetivo',
      'target': 'Objetivo',
      'repeat': 'Repetición',
      'once': 'Una vez',
      'daily': 'Diariamente',
      'weekly': 'Semanalmente',
      'customInterval': 'Intervalo personalizado',
      'daysOfWeek': 'Días de la semana',
      'intervalDays': 'Intervalo en días',
      'startsOn': 'Empieza el',
      'mondayShort': 'Lun',
      'tuesdayShort': 'Mar',
      'wednesdayShort': 'Mié',
      'thursdayShort': 'Jue',
      'fridayShort': 'Vie',
      'saturdayShort': 'Sáb',
      'sundayShort': 'Dom',
      'modeDetails': 'Detalles y alcance del modo',
      'entireSite': 'Toda la sede',
      'startTime': 'Hora de inicio',
      'endTime': 'Hora de fin',
      'internalRoutines': 'Rutinas del modo',
      'routineName': 'Nombre de la rutina',
      'triggerTime': 'Hora de ejecución',
      'addRoutine': 'Agregar rutina',
      'automationPolicies': 'Metas y políticas de notificación',
      'applyRuleProfile': 'Aplicar un perfil de reglas de alerta',
      'ruleProfile': 'Perfil de reglas',
      'applyNotificationPreference': 'Aplicar mis preferencias de notificación',
      'preserveCriticalSound': 'Mantener sonido en alertas críticas',
      'createMode': 'Crear modo',
      'activate': 'Activar',
      'spaces': 'Espacios',
      'sites': 'Sedes',
      'assignments': 'Asignaciones',
      'noSites': 'No hay sedes configuradas',
      'noRooms': 'No hay habitaciones configuradas',
      'noAssignments': 'No hay dispositivos asignados',
      'newSite': 'Nueva sede',
      'address': 'Dirección',
      'type': 'Tipo',
      'newRoom': 'Nueva habitación',
      'floor': 'Piso',
      'assignDevice': 'Asignar dispositivo',
      'noRoom': 'Sin habitación',
      'unassign': 'Desasignar',
      'delete': 'Eliminar',
      'deleteSite': 'Eliminar sede',
      'deleteSiteWarning':
          'Esto puede afectar sus habitaciones y asignaciones.',
      'deleteRoom': 'Eliminar habitación',
      'deleteRoomWarning':
          'Los dispositivos asignados pueden quedar sin habitación.',
      'notifications': 'Notificaciones',
      'alertsCenter': 'Centro de alertas',
      'alertsDescription':
          'Revisa alertas, automatiza reglas y elige cómo te contacta EnergyCore.',
      'inbox': 'Bandeja',
      'rules': 'Reglas',
      'preferences': 'Preferencias',
      'noAlerts': 'Tu bandeja está limpia',
      'noRules': 'No hay reglas de alerta',
      'markRead': 'Marcar leída',
      'resolve': 'Resolver',
      'dismiss': 'Descartar',
      'newRule': 'Nueva regla',
      'metric': 'Métrica',
      'condition': 'Condición',
      'threshold': 'Umbral',
      'severity': 'Severidad',
      'pushNotifications': 'Notificaciones push',
      'inApp': 'Notificaciones en la aplicación',
      'criticalOnly': 'Solo alertas críticas',
      'quietHours': 'Horario silencioso',
      'dailySummary': 'Resumen diario',
      'weeklySummary': 'Resumen semanal',
      'monthlyReport': 'Reporte mensual',
      'savePreferences': 'Guardar preferencias',
      'energyCenter': 'Inteligencia energética',
      'energyCenterDescription':
          'Explora consumo en vivo, historial, reportes y metas de reducción.',
      'consumption': 'Consumo',
      'history': 'Historial',
      'reports': 'Reportes',
      'goals': 'Metas',
      'noReadings': 'No hay lecturas de energía',
      'searchDevice': 'Buscar por dispositivo',
      'unknownDate': 'Fecha desconocida',
      'noReports': 'No hay reportes generados',
      'report': 'Reporte',
      'total': 'Total',
      'average': 'Promedio',
      'peak': 'Pico',
      'generateReport': 'Generar reporte',
      'startDate': 'Fecha inicial',
      'endDate': 'Fecha final',
      'generate': 'Generar',
      'noGoals': 'No hay metas energéticas',
      'newGoal': 'Nueva meta',
      'targetKwh': 'Objetivo (kWh)',
      'deadline': 'Fecha límite',
      'service': 'Servicio',
      'support': 'Soporte',
      'maintenance': 'Mantenimiento',
      'noSupportTickets': 'No hay solicitudes de soporte',
      'noMaintenanceTickets': 'No hay mantenimientos programados',
      'newTicket': 'Nueva solicitud',
      'subject': 'Asunto',
      'priority': 'Prioridad',
      'send': 'Enviar',
      'scheduleMaintenance': 'Programar mantenimiento',
      'scheduledDate': 'Fecha programada',
      'complete': 'Completar',
      'billing': 'Facturación',
      'plans': 'Planes',
      'payments': 'Pagos',
      'invoices': 'Comprobantes',
      'noPlans': 'No hay planes disponibles',
      'noPayments': 'Aún no hay pagos',
      'noInvoices': 'Aún no hay comprobantes',
      'currentPlan': 'Plan actual',
      'choosePlan': 'Elegir plan',
      'cancelPlan': 'Cancelar plan',
      'cancelSubscription': 'Cancelar suscripción',
      'cancelSubscriptionWarning':
          'Tu acceso puede cambiar al terminar el periodo actual.',
      'confirm': 'Confirmar',
      'cardHolder': 'Titular de la tarjeta',
      'cardNumber': 'Número de tarjeta',
      'subscribe': 'Suscribirme',
      'active': 'Activos',
      'security': 'Seguridad',
      'access': 'Accesos',
      'platform': 'Plataforma',
      'editProfile': 'Editar perfil',
      'changePassword': 'Cambiar contraseña',
      'changePasswordDescription': 'Recibe un enlace seguro por correo.',
      'deleteAccount': 'Eliminar cuenta',
      'deleteAccountWarning':
          'Esto elimina permanentemente tu cuenta de EnergyCore.',
      'accessRestricted':
          'La administración de accesos está disponible solo para perfiles autorizados.',
      'platformTitle': 'Un solo sistema energético conectado',
      'platformDescription':
          'EnergyCore conecta espacios, dispositivos, automatización, alertas y decisiones mediante la plataforma Teralume.',
      'energyMonitoring': 'Monitoreo energético en tiempo real',
      'deviceAutomation': 'Dispositivos, grupos, rutinas y modos',
      'smartAlerts': 'Reglas y alertas inteligentes',
      'reportsAndGoals': 'Reportes y metas energéticas',
      'integratedSupport': 'Soporte y mantenimiento integrados',
      'operationalCenterDescription':
          'Todo lo importante de tu operación energética en una vista clara.',
      'setupGuide': 'Completa la configuración',
      'welcomeEnergyCore': 'Bienvenido a EnergyCore',
      'homeEmptyDescription':
          'Conecta el backend y agrega espacios y dispositivos para ver tu operación en acción.',
      'unread': 'Sin leer',
      'activeRules': 'Reglas activas',
      'noActiveMode': 'Sin modo activo',
      'available': 'Disponibles',
      'open': 'Abiertos',
      'spacesDescription': 'Sedes, habitaciones y asignaciones',
      'serviceDescription': 'Soporte y mantenimiento',
      'billingDescription': 'Planes e historial de pagos',
      'accountDescription': 'Perfil, seguridad y accesos',
      'moreDescription': 'Administra el resto de tu experiencia EnergyCore.',
      'edit': 'Editar',
      'addDevice': 'Agregar dispositivo',
      'createDevice': 'Crear dispositivo',
      'editDevice': 'Editar dispositivo',
      'powerWatts': 'Potencia (W)',
      'deleteDevice': 'Eliminar dispositivo',
      'deleteDeviceWarning': 'Se eliminarán el dispositivo y sus vínculos.',
      'editGroup': 'Editar grupo',
      'deleteGroup': 'Eliminar grupo',
      'deleteGroupWarning': 'Se eliminará el grupo, pero no sus dispositivos.',
      'deleteRoutine': 'Eliminar rutina',
      'deleteRoutineWarning': 'Esta automatización dejará de ejecutarse.',
      'preview': 'Vista previa',
      'archive': 'Archivar',
      'affectedDevices': 'Dispositivos afectados',
      'ignoredDevices': 'Dispositivos omitidos',
      'close': 'Cerrar',
      'archiveMode': 'Archivar modo',
      'archiveModeWarning':
          'Este modo de operación dejará de estar disponible.',
      'editSite': 'Editar sede',
      'editRoom': 'Editar habitación',
      'move': 'Mover',
      'moveDevice': 'Mover dispositivo',
      'deleteTicket': 'Eliminar solicitud',
      'deleteTicketWarning':
          'Esta solicitud de soporte se eliminará permanentemente.',
      'deleteMaintenance': 'Eliminar mantenimiento',
      'details': 'Detalles',
      'export': 'Exportar',
      'deviceBreakdown': 'Desglose por dispositivo',
      'copiedToClipboard': 'CSV copiado al portapapeles.',
      'editGoal': 'Editar meta',
      'currentKwh': 'Actual (kWh)',
      'status': 'Estado',
      'dateRange': 'Rango de fechas',
      'all': 'Todos',
      'newest': 'Más recientes',
      'oldest': 'Más antiguos',
      'power_desc': 'Mayor potencia',
      'power_asc': 'Menor potencia',
      'powerRange': 'Rango de potencia',
      'minimum': 'Mínimo',
      'maximum': 'Máximo',
      'apply': 'Aplicar',
      'samplingInterval': 'Intervalo de muestreo',
      'seconds': 'segundos',
      'critical': 'Críticas',
      'evidence': 'Evidencia',
      'explanation': 'Explicación',
      'recommendedAction': 'Acción recomendada',
      'deleteAlert': 'Eliminar alerta',
      'deleteAlertWarning': 'Esta alerta se eliminará permanentemente.',
      'inactive': 'Inactivo',
      'newProfile': 'Nuevo perfil',
      'evaluateRules': 'Evaluar reglas',
      'deleteRule': 'Eliminar regla',
      'deleteRuleWarning': 'Esta regla de alerta se eliminará permanentemente.',
      'mode': 'Modo',
      'sensitivity': 'Sensibilidad',
      'observedValue': 'Valor observado',
      'evaluate': 'Evaluar',
      'evaluationResult': 'Resultado de evaluación',
      'minimumLevel': 'Nivel mínimo',
      'toastNotifications': 'Notificaciones flotantes',
      'dashboardNotifications': 'Notificaciones en el panel',
      'allowedLevels': 'Niveles de alerta permitidos',
      'allowedSources': 'Fuentes permitidas',
      'criticalBreaksQuietHours':
          'Las alertas críticas interrumpen las horas de silencio',
      'routineNightSilence': 'Silenciar alertas de rutinas por la noche',
      'goalDeadlineAlerts': 'Alertas de vencimiento de metas energéticas',
      'maintenanceDeviceAlerts': 'Alertas de mantenimiento de dispositivos',
      'systemRecommendations': 'Recomendaciones del sistema',
      'deliveryMode': 'Modo de entrega predeterminado',
      'groupSimilarAlerts': 'Agrupar alertas similares',
      'reminders': 'Recordatorios',
      'cooldownMinutes': 'Espera (minutos)',
      'maxAlertsPerHour': 'Máximo de alertas por hora',
      'resetPasswordTitle': 'Establece una nueva contraseña',
      'resetPassword': 'Restablecer contraseña',
      'recoveryToken': 'Token de recuperación',
      'confirmPassword': 'Confirmar contraseña',
      'passwordsDoNotMatch': 'Las contraseñas no coinciden.',
      'haveRecoveryToken': 'Ya tengo un token de recuperación',
      'passwordResetSuccess':
          'Contraseña actualizada. Ya puedes iniciar sesión.',
      'system': 'Sistema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'chooseAPlan': 'Elige un plan para continuar',
      'exportInvoice': 'Exportar comprobante',
      'invoiceCopied': 'Comprobante copiado al portapapeles.',
      'newAlert': 'Nueva alerta',
      'title': 'Título',
      'message': 'Mensaje',
      'upgradePlanFeature': 'Mejora tu plan para usar esta función.',
      'searchAddress': 'Buscar dirección',
    },
    'pt': {
      'appName': 'EnergyCore',
      'tagline': 'Energia inteligente. Decisões claras.',
      'authVisualMessage':
          'Monitore o consumo, reduza desperdícios e mantenha cada espaço sob controle.',
      'signIn': 'Entrar',
      'signUp': 'Criar conta',
      'recover': 'Recuperar senha',
      'welcome': 'Bem-vindo de volta',
      'createTitle': 'Energize o seu espaço',
      'recoverTitle': 'Recupere seu acesso',
      'email': 'E-mail',
      'password': 'Senha',
      'fullName': 'Nome completo',
      'forgot': 'Esqueceu sua senha?',
      'noAccount': 'Novo no EnergyCore?',
      'hasAccount': 'Já possui uma conta?',
      'backToLogin': 'Voltar para entrar',
      'sendRecovery': 'Enviar e-mail de recuperação',
      'recoverySent': 'Se a conta existir, enviaremos as instruções.',
      'required': 'Este campo é obrigatório.',
      'invalidEmail': 'Digite um e-mail válido.',
      'shortPassword': 'Use pelo menos 8 caracteres.',
      'showPassword': 'Mostrar senha',
      'hidePassword': 'Ocultar senha',
      'home': 'Início',
      'energy': 'Energia',
      'devices': 'Dispositivos',
      'alerts': 'Alertas',
      'more': 'Mais',
      'greeting': 'Olá',
      'overview': 'Sua energia, agora',
      'live': 'AO VIVO',
      'currentPower': 'Potência atual',
      'todayEnergy': 'Energia hoje',
      'todayCost': 'Custo hoje',
      'monthlyProjection': 'Projeção mensal',
      'efficiency': 'Eficiência',
      'activeDevices': 'Dispositivos ativos',
      'trend': 'Tendência de consumo',
      'topDevices': 'Dispositivos de maior consumo',
      'rooms': 'Consumo por ambiente',
      'recommendation': 'Dica de energia',
      'noData': 'Ainda não há dados de energia disponíveis.',
      'retry': 'Tentar novamente',
      'offline': 'É necessário ter internet para atualizar o EnergyCore.',
      'loadError': 'Não foi possível carregar seus dados de energia.',
      'language': 'Idioma',
      'appearance': 'Aparência',
      'systemTheme': 'Segue as configurações do dispositivo',
      'account': 'Conta',
      'signOut': 'Sair',
      'profile': 'Perfil',
      'emptyHint':
          'Crie o primeiro item para conectar sua operação energética.',
      'refresh': 'Atualizar',
      'operations': 'Operações',
      'deviceControlTitle': 'Operações conectadas',
      'deviceControlDescription':
          'Controle dispositivos, grupos, rotinas e modos em um só lugar.',
      'groups': 'Grupos',
      'routines': 'Rotinas',
      'modes': 'Modos',
      'noDevices': 'Nenhum dispositivo conectado',
      'noGroups': 'Nenhum grupo de dispositivos',
      'noRoutines': 'Nenhuma rotina programada',
      'noModes': 'Nenhum modo de operação',
      'newMode': 'Novo modo',
      'turnOn': 'Ligar',
      'turnOff': 'Desligar',
      'pairDevice': 'Parear dispositivo',
      'pairingCode': 'Código de pareamento',
      'deviceName': 'Nome do dispositivo',
      'room': 'Ambiente',
      'connect': 'Conectar',
      'cancel': 'Cancelar',
      'newGroup': 'Novo grupo',
      'name': 'Nome',
      'description': 'Descrição',
      'save': 'Salvar',
      'newRoutine': 'Nova rotina',
      'schedule': 'Horário',
      'runNow': 'Executar agora',
      'allDay': 'Dia inteiro',
      'targetType': 'Tipo de alvo',
      'target': 'Alvo',
      'repeat': 'Repetição',
      'once': 'Uma vez',
      'daily': 'Diariamente',
      'weekly': 'Semanalmente',
      'customInterval': 'Intervalo personalizado',
      'daysOfWeek': 'Dias da semana',
      'intervalDays': 'Intervalo em dias',
      'startsOn': 'Começa em',
      'mondayShort': 'Seg',
      'tuesdayShort': 'Ter',
      'wednesdayShort': 'Qua',
      'thursdayShort': 'Qui',
      'fridayShort': 'Sex',
      'saturdayShort': 'Sáb',
      'sundayShort': 'Dom',
      'modeDetails': 'Detalhes e escopo do modo',
      'entireSite': 'Todo o local',
      'startTime': 'Hora de início',
      'endTime': 'Hora de término',
      'internalRoutines': 'Rotinas do modo',
      'routineName': 'Nome da rotina',
      'triggerTime': 'Horário de execução',
      'addRoutine': 'Adicionar rotina',
      'automationPolicies': 'Metas e políticas de notificação',
      'applyRuleProfile': 'Aplicar um perfil de regras de alerta',
      'ruleProfile': 'Perfil de regras',
      'applyNotificationPreference':
          'Aplicar minhas preferências de notificação',
      'preserveCriticalSound': 'Manter som em alertas críticos',
      'createMode': 'Criar modo',
      'activate': 'Ativar',
      'spaces': 'Espaços',
      'sites': 'Locais',
      'assignments': 'Atribuições',
      'noSites': 'Nenhum local configurado',
      'noRooms': 'Nenhum ambiente configurado',
      'noAssignments': 'Nenhum dispositivo atribuído',
      'newSite': 'Novo local',
      'address': 'Endereço',
      'type': 'Tipo',
      'newRoom': 'Novo ambiente',
      'floor': 'Andar',
      'assignDevice': 'Atribuir dispositivo',
      'noRoom': 'Sem ambiente',
      'unassign': 'Remover atribuição',
      'delete': 'Excluir',
      'deleteSite': 'Excluir local',
      'deleteSiteWarning': 'Isso pode afetar ambientes e atribuições.',
      'deleteRoom': 'Excluir ambiente',
      'deleteRoomWarning': 'Dispositivos atribuídos podem ficar sem ambiente.',
      'notifications': 'Notificações',
      'alertsCenter': 'Central de alertas',
      'alertsDescription':
          'Revise alertas, automatize regras e escolha como o EnergyCore avisa você.',
      'inbox': 'Caixa de entrada',
      'rules': 'Regras',
      'preferences': 'Preferências',
      'noAlerts': 'Sua caixa de entrada está limpa',
      'noRules': 'Nenhuma regra de alerta',
      'markRead': 'Marcar como lido',
      'resolve': 'Resolver',
      'dismiss': 'Descartar',
      'newRule': 'Nova regra',
      'metric': 'Métrica',
      'condition': 'Condição',
      'threshold': 'Limite',
      'severity': 'Severidade',
      'pushNotifications': 'Notificações push',
      'inApp': 'Notificações no aplicativo',
      'criticalOnly': 'Somente alertas críticos',
      'quietHours': 'Horário silencioso',
      'dailySummary': 'Resumo diário',
      'weeklySummary': 'Resumo semanal',
      'monthlyReport': 'Relatório mensal',
      'savePreferences': 'Salvar preferências',
      'energyCenter': 'Inteligência energética',
      'energyCenterDescription':
          'Explore consumo ao vivo, histórico, relatórios e metas.',
      'consumption': 'Consumo',
      'history': 'Histórico',
      'reports': 'Relatórios',
      'goals': 'Metas',
      'noReadings': 'Nenhuma leitura de energia',
      'searchDevice': 'Buscar por dispositivo',
      'unknownDate': 'Data desconhecida',
      'noReports': 'Nenhum relatório gerado',
      'report': 'Relatório',
      'total': 'Total',
      'average': 'Média',
      'peak': 'Pico',
      'generateReport': 'Gerar relatório',
      'startDate': 'Data inicial',
      'endDate': 'Data final',
      'generate': 'Gerar',
      'noGoals': 'Nenhuma meta energética',
      'newGoal': 'Nova meta',
      'targetKwh': 'Meta (kWh)',
      'deadline': 'Prazo',
      'service': 'Serviço',
      'support': 'Suporte',
      'maintenance': 'Manutenção',
      'noSupportTickets': 'Nenhum chamado de suporte',
      'noMaintenanceTickets': 'Nenhuma manutenção programada',
      'newTicket': 'Novo chamado',
      'subject': 'Assunto',
      'priority': 'Prioridade',
      'send': 'Enviar',
      'scheduleMaintenance': 'Agendar manutenção',
      'scheduledDate': 'Data agendada',
      'complete': 'Concluir',
      'billing': 'Faturamento',
      'plans': 'Planos',
      'payments': 'Pagamentos',
      'invoices': 'Faturas',
      'noPlans': 'Nenhum plano disponível',
      'noPayments': 'Ainda não há pagamentos',
      'noInvoices': 'Ainda não há faturas',
      'currentPlan': 'Plano atual',
      'choosePlan': 'Escolher plano',
      'cancelPlan': 'Cancelar plano',
      'cancelSubscription': 'Cancelar assinatura',
      'cancelSubscriptionWarning':
          'Seu acesso pode mudar ao fim do período atual.',
      'confirm': 'Confirmar',
      'cardHolder': 'Titular do cartão',
      'cardNumber': 'Número do cartão',
      'subscribe': 'Assinar',
      'active': 'Ativos',
      'security': 'Segurança',
      'access': 'Acessos',
      'platform': 'Plataforma',
      'editProfile': 'Editar perfil',
      'changePassword': 'Alterar senha',
      'changePasswordDescription': 'Receba um link seguro por e-mail.',
      'deleteAccount': 'Excluir conta',
      'deleteAccountWarning':
          'Isso remove permanentemente sua conta EnergyCore.',
      'accessRestricted':
          'A gestão de acessos está disponível apenas para perfis autorizados.',
      'platformTitle': 'Um único sistema energético conectado',
      'platformDescription':
          'O EnergyCore conecta espaços, dispositivos, automação, alertas e decisões pela plataforma Teralume.',
      'energyMonitoring': 'Monitoramento energético em tempo real',
      'deviceAutomation': 'Dispositivos, grupos, rotinas e modos',
      'smartAlerts': 'Regras e alertas inteligentes',
      'reportsAndGoals': 'Relatórios e metas energéticas',
      'integratedSupport': 'Suporte e manutenção integrados',
      'operationalCenterDescription':
          'Tudo o que importa na sua operação energética em uma visão clara.',
      'setupGuide': 'Conclua a configuração',
      'welcomeEnergyCore': 'Bem-vindo ao EnergyCore',
      'homeEmptyDescription':
          'Conecte o backend e adicione espaços e dispositivos para ver sua operação em ação.',
      'unread': 'Não lidos',
      'activeRules': 'Regras ativas',
      'noActiveMode': 'Nenhum modo ativo',
      'available': 'Disponíveis',
      'open': 'Abertos',
      'spacesDescription': 'Locais, ambientes e atribuições',
      'serviceDescription': 'Suporte e manutenção',
      'billingDescription': 'Planos e histórico de pagamentos',
      'accountDescription': 'Perfil, segurança e acessos',
      'moreDescription': 'Gerencie o restante da sua experiência EnergyCore.',
      'edit': 'Editar',
      'addDevice': 'Adicionar dispositivo',
      'createDevice': 'Criar dispositivo',
      'editDevice': 'Editar dispositivo',
      'powerWatts': 'Potência (W)',
      'deleteDevice': 'Excluir dispositivo',
      'deleteDeviceWarning': 'O dispositivo e seus vínculos serão removidos.',
      'editGroup': 'Editar grupo',
      'deleteGroup': 'Excluir grupo',
      'deleteGroupWarning':
          'O grupo será removido sem excluir seus dispositivos.',
      'deleteRoutine': 'Excluir rotina',
      'deleteRoutineWarning': 'Esta automação deixará de ser executada.',
      'preview': 'Visualizar',
      'archive': 'Arquivar',
      'affectedDevices': 'Dispositivos afetados',
      'ignoredDevices': 'Dispositivos ignorados',
      'close': 'Fechar',
      'archiveMode': 'Arquivar modo',
      'archiveModeWarning':
          'Este modo de operação deixará de estar disponível.',
      'editSite': 'Editar unidade',
      'editRoom': 'Editar ambiente',
      'move': 'Mover',
      'moveDevice': 'Mover dispositivo',
      'deleteTicket': 'Excluir chamado',
      'deleteTicketWarning':
          'Este chamado de suporte será excluído permanentemente.',
      'deleteMaintenance': 'Excluir manutenção',
      'details': 'Detalhes',
      'export': 'Exportar',
      'deviceBreakdown': 'Detalhamento por dispositivo',
      'copiedToClipboard': 'CSV copiado para a área de transferência.',
      'editGoal': 'Editar meta',
      'currentKwh': 'Atual (kWh)',
      'status': 'Status',
      'dateRange': 'Intervalo de datas',
      'all': 'Todos',
      'newest': 'Mais recentes',
      'oldest': 'Mais antigos',
      'power_desc': 'Maior potência',
      'power_asc': 'Menor potência',
      'powerRange': 'Faixa de potência',
      'minimum': 'Mínimo',
      'maximum': 'Máximo',
      'apply': 'Aplicar',
      'samplingInterval': 'Intervalo de amostragem',
      'seconds': 'segundos',
      'critical': 'Críticos',
      'evidence': 'Evidência',
      'explanation': 'Explicação',
      'recommendedAction': 'Ação recomendada',
      'deleteAlert': 'Excluir alerta',
      'deleteAlertWarning': 'Este alerta será excluído permanentemente.',
      'inactive': 'Inativo',
      'newProfile': 'Novo perfil',
      'evaluateRules': 'Avaliar regras',
      'deleteRule': 'Excluir regra',
      'deleteRuleWarning':
          'Esta regra de alerta será excluída permanentemente.',
      'mode': 'Modo',
      'sensitivity': 'Sensibilidade',
      'observedValue': 'Valor observado',
      'evaluate': 'Avaliar',
      'evaluationResult': 'Resultado da avaliação',
      'minimumLevel': 'Nível mínimo',
      'toastNotifications': 'Notificações flutuantes',
      'dashboardNotifications': 'Notificações no painel',
      'allowedLevels': 'Níveis de alerta permitidos',
      'allowedSources': 'Fontes permitidas',
      'criticalBreaksQuietHours':
          'Alertas críticos interrompem o horário silencioso',
      'routineNightSilence': 'Silenciar alertas de rotinas à noite',
      'goalDeadlineAlerts': 'Alertas de prazo das metas de energia',
      'maintenanceDeviceAlerts': 'Alertas de manutenção dos dispositivos',
      'systemRecommendations': 'Recomendações do sistema',
      'deliveryMode': 'Modo de entrega padrão',
      'groupSimilarAlerts': 'Agrupar alertas semelhantes',
      'reminders': 'Lembretes',
      'cooldownMinutes': 'Espera (minutos)',
      'maxAlertsPerHour': 'Máximo de alertas por hora',
      'resetPasswordTitle': 'Defina uma nova senha',
      'resetPassword': 'Redefinir senha',
      'recoveryToken': 'Token de recuperação',
      'confirmPassword': 'Confirmar senha',
      'passwordsDoNotMatch': 'As senhas não coincidem.',
      'haveRecoveryToken': 'Já tenho um token de recuperação',
      'passwordResetSuccess': 'Senha atualizada. Você já pode entrar.',
      'system': 'Sistema',
      'light': 'Claro',
      'dark': 'Escuro',
      'chooseAPlan': 'Escolha um plano para continuar',
      'exportInvoice': 'Exportar fatura',
      'invoiceCopied': 'Fatura copiada para a área de transferência.',
      'newAlert': 'Novo alerta',
      'title': 'Título',
      'message': 'Mensagem',
      'upgradePlanFeature': 'Melhore seu plano para usar este recurso.',
      'searchAddress': 'Buscar endereço',
    },
  };
}

final class _StringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _StringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture(AppStrings(locale));

  @override
  bool shouldReload(_StringsDelegate old) => false;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
